// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FeedbackforminvalidDatashortFeedbackResponseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void feedbackforminvalidDatashortFeedbackResponse() {
    driver.get("https://www.sportchek.ca/");
    driver.manage().window().setSize(new Dimension(1296, 696));
    driver.findElement(By.cssSelector(".page-nav__item:nth-child(7) .main-menu__text")).click();
    driver.findElement(By.linkText("Snowboards")).click();
    {
      WebElement element = driver.findElement(By.linkText("Snowboards"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,216.6666717529297)");
    js.executeScript("window.scrollTo(0,441.3333435058594)");
    driver.findElement(By.cssSelector(".product-grid__list-item:nth-child(2) .product-grid-image")).click();
    js.executeScript("window.scrollTo(0,1376)");
    js.executeScript("window.scrollTo(0,1650.6666259765625)");
    js.executeScript("window.scrollTo(0,1825.3333740234375)");
    js.executeScript("window.scrollTo(0,2822.666748046875)");
    js.executeScript("window.scrollTo(0,3068.666748046875)");
    js.executeScript("window.scrollTo(0,3326)");
    js.executeScript("window.scrollTo(0,3366)");
    {
      WebElement element = driver.findElement(By.cssSelector(".bv-write-review-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".bv-write-review-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,10)");
    driver.findElement(By.cssSelector("#bv-radio-rating-5 > span:nth-child(1)")).click();
    driver.findElement(By.id("bv-text-field-title")).click();
    driver.findElement(By.id("bv-text-field-title")).sendKeys("Great features!");
    driver.findElement(By.id("bv-textarea-field-reviewtext")).click();
    js.executeScript("window.scrollTo(0,9.333333015441895)");
    driver.findElement(By.id("bv-textarea-field-reviewtext")).sendKeys("badass with a hint of saas!");
    driver.findElement(By.id("bv-radio-isrecommended-true-label")).click();
    driver.findElement(By.id("bv-text-field-usernickname")).click();
    driver.findElement(By.id("bv-text-field-usernickname")).sendKeys("lovepreet");
    driver.findElement(By.id("bv-select-field-contextdatavalue_WhereDidYouPurchase_1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("bv-select-field-contextdatavalue_WhereDidYouPurchase_1"));
      dropdown.findElement(By.xpath("//option[. = 'Online']")).click();
    }
    driver.findElement(By.id("bv-select-field-contextdatavalue_StaffIndicator")).click();
    {
      WebElement dropdown = driver.findElement(By.id("bv-select-field-contextdatavalue_StaffIndicator"));
      dropdown.findElement(By.xpath("//option[. = 'No']")).click();
    }
    driver.findElement(By.id("bv-select-field-contextdatavalue_DidYouReceiveThisProductForFree")).click();
    {
      WebElement dropdown = driver.findElement(By.id("bv-select-field-contextdatavalue_DidYouReceiveThisProductForFree"));
      dropdown.findElement(By.xpath("//option[. = 'No']")).click();
    }
    driver.findElement(By.id("bv-radio-netpromoterscore-10-label")).click();
    driver.findElement(By.id("bv-checkbox-reviews-termsAndConditions")).click();
    driver.findElement(By.name("bv-submit-button")).click();
    js.executeScript("window.scrollTo(0,9.333333015441895)");
  }
}
