// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FeedbackformvalidDatafootwearTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void feedbackformvalidDatafootwear() {
    driver.get("https://www.sportchek.ca/");
    driver.manage().window().setSize(new Dimension(1296, 696));
    {
      WebElement element = driver.findElement(By.cssSelector(".page-nav__item:nth-child(6) .main-menu__text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".page-nav__item:nth-child(6) .main-menu__text")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".page-nav__section:nth-child(2) .page-nav__item:nth-child(1) > .page-nav__link")).click();
    driver.findElement(By.cssSelector(".product-grid__list-item:nth-child(2) .product-grid-image")).click();
    js.executeScript("window.scrollTo(0,200)");
    js.executeScript("window.scrollTo(0,400)");
    js.executeScript("window.scrollTo(0,1500)");
    js.executeScript("window.scrollTo(0,2190.666748046875)");
    js.executeScript("window.scrollTo(0,2338.666748046875)");
    js.executeScript("window.scrollTo(0,2700)");
    driver.findElement(By.cssSelector(".bv-write-review")).click();
    js.executeScript("window.scrollTo(0,2511.333251953125)");
    driver.findElement(By.cssSelector("#bv-radio-rating-5 > span:nth-child(1)")).click();
    driver.findElement(By.id("bv-text-field-title")).click();
    driver.findElement(By.id("bv-text-field-title")).sendKeys("Wonderful features!");
    driver.findElement(By.id("bv-textarea-field-reviewtext")).click();
    driver.findElement(By.id("bv-textarea-field-reviewtext")).sendKeys("I purchased this 3 months ago, they are still in perfect condition, great for hiking in all weathers and also very durable. I love these shoes!!!");
    driver.findElement(By.id("bv-radio-isrecommended-true-label")).click();
    driver.findElement(By.id("bv-text-field-usernickname")).click();
    driver.findElement(By.id("bv-text-field-usernickname")).sendKeys("man_meet20103004000");
    driver.findElement(By.id("bv-email-field-hostedauthentication_authenticationemail")).click();
    driver.findElement(By.id("bv-email-field-hostedauthentication_authenticationemail")).sendKeys("rajmeet.gill@gmail.com");
    driver.findElement(By.id("bv-select-field-contextdatavalue_WhereDidYouPurchase_1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("bv-select-field-contextdatavalue_WhereDidYouPurchase_1"));
      dropdown.findElement(By.xpath("//option[. = 'Online']")).click();
    }
    driver.findElement(By.id("bv-select-field-contextdatavalue_StaffIndicator")).click();
    {
      WebElement dropdown = driver.findElement(By.id("bv-select-field-contextdatavalue_StaffIndicator"));
      dropdown.findElement(By.xpath("//option[. = 'No']")).click();
    }
    driver.findElement(By.id("bv-select-field-contextdatavalue_DidYouReceiveThisProductForFree")).click();
    {
      WebElement dropdown = driver.findElement(By.id("bv-select-field-contextdatavalue_DidYouReceiveThisProductForFree"));
      dropdown.findElement(By.xpath("//option[. = 'No']")).click();
    }
    driver.findElement(By.id("bv-radio-netpromoterscore-10-label")).click();
    driver.findElement(By.id("bv-checkbox-reviews-termsAndConditions")).click();
    driver.findElement(By.name("bv-submit-button")).click();
    driver.findElement(By.id("bv-text-field-usernickname")).sendKeys("behrouz1");
    assertThat(driver.findElement(By.id("bv-mbox-label-text")).getText(), is("Your review was submitted!"));
  }
}
