// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PicUploadValidTest1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void picUploadValidTest1() {
    driver.get("https://www.sportchek.ca/");
    driver.manage().window().setSize(new Dimension(1509, 943));
    js.executeScript("window.scrollTo(0,2635)");
    js.executeScript("window.scrollTo(0,3135)");
    driver.findElement(By.cssSelector(".sc-1717v0r-1")).click();
    driver.findElement(By.cssSelector(".g8qrok-1")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".g8qrok-2 > .g8qrok-3"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".g8qrok-2"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".g8qrok-2")).click();
    driver.findElement(By.cssSelector(".sc-1s7g1qu-1")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("crl8-homepage-carousel-userForm-displayName")).sendKeys("Huda Abbas");
    driver.findElement(By.id("crl8-homepage-carousel-userForm-emailAddress")).click();
    driver.findElement(By.id("crl8-homepage-carousel-userForm-emailAddress")).sendKeys("1•••••••••••••••r@gmail.com");
    driver.findElement(By.id("crl8-homepage-carousel-userForm-termsAndConditions")).click();
    driver.findElement(By.cssSelector(".sc-1s7g1qu-2")).click();
    assertThat(driver.findElement(By.cssSelector(".i37uxa-1")).getText(), is("SUCCESS!"));
  }
}
