// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ViewProductDescriptionValidTest1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void viewProductDescriptionValidTest1() {
    driver.get("https://www.sportchek.ca/");
    driver.manage().window().setSize(new Dimension(1509, 943));
    {
      WebElement element = driver.findElement(By.cssSelector(".enterprise-header__section:nth-child(3) a:nth-child(1) > font"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,638)");
    driver.findElement(By.linkText("The North Face Kids\' Salty Dog Beanie")).click();
    js.executeScript("window.scrollTo(0,429)");
    driver.findElement(By.cssSelector(".product-detail-description-link:nth-child(2)")).click();
    js.executeScript("window.scrollTo(0,1168)");
    js.executeScript("window.scrollTo(0,790.5)");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".product-description-blurb"));
      assert(elements.size() > 0);
    }
  }
}
